policy:
  approval:
    - small changes auto-approve
    - few commits auto-approve
    - check commit messages

approval_rules:
  - name: small changes auto-approve
    requires:
      count: 0
    if:
      changed_files_count:
        total: "< 20"

  - name: few commits auto-approve
    requires:
      count: 0
    if:
      commit_count:
        total: "<= 10"

  - name: check commit messages
    requires:
      count: 1
    if:
      commit_messages:
        mode: all
        scope: subject
        matches:
          - "^(feat|fix|docs):"
